trigger: 
 - main

pool:
   vmImage: 'macOS-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.23.0'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-v all'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: Artefatto